language: c
dist: xenial
sudo: required
addons:
  apt:
    update: true
    packages:
    - parted
    - wget
    - dosfstools
    - zip
before_script:
- sudo .travis_build/before_build.sh
script:
- export IMAGE="sopine_arch_headless.img"
- sudo ./build_image.sh "${IMAGE}" "4G" "aarch64" "http://archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz"
- sudo xz -k -v -1 --compress -T 2 ${IMAGE}
deploy:
  provider: releases
  api_key:
    secure: gKMrqF32JJxopFWNF+Tuv4B5H7ZifyOZyUsLLdW/wutHQFdPRya9WI7VpFGePAh1pq70dNH3m2IzVZRkd9VCFmUwvuAeeK35t5h+GCEHI2BOjyF6eYq4NW0v2n31P655SvoFgM/536Ords3PDDPfw/3t8ef9b4em0qdhWt4nrFjn7qYDpwAPSKf8VDvtu+qE98NW34Rnueof2kzRcLFHiGfbLRwPPoDO25UXaAssqc9ejO4iqN7AyjoHVuCgsMgDSSNkhDD8rROzsFOGZ87yUhvK+Svwhq80Go4CSL6SzHP6cd2/ig3uCn4U81jwLQnP7gi09Tc5tLTsUjZINV+QGRylGjznzoVXB0VD4eQhUgeF5DOPJhatsqeNSoQT7YhYW4EunmuMRcVW/DNmTzv3PBPLGkSrOUiOp2h8jo9TCxS/mpm7QU2Zs+QVNZvZm7O5NDw6jr0wYg+Ljf8HoI5DvoNqfmrEKqxehrAVPP2Ye3Mw0u2i7L+aq5P6DeN/+OII7u4ud7GsetOiIND9TdqvwvYPUb6mdRdH/6Y4x4ffJq6eRPB8rQ2KbRvf7a23ACaU59+Ozq+c9OKtdDTyos+YppjyjcRCZ8gUwKeh94TFLzf9hozZvuen9nF2W4YcMnIR90kRW9N2Mna/mAaPeFb6Do/RiwfX4AWsTYlFUkNS0n4=
  file: "${IMAGE}.xz"
  on:
    repo: jeanlego/pine64
    branch: heads/mainline
